config/routes.rb
Rails.application.routes.draw do
  get 'my-events', to: 'users#show', as: :my_events
  get 'events/user/:id', to: 'users#show', as: :user
  devise_for :users, controllers: { registrations: 'registrations' }
  root "events#index"
  resources :events
  resources :invitations
  post 'event_attendances', to: 'event_attendances#create'
  delete 'event_attendances', to: 'event_attendances#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class DateValidator < ActiveModel::Validator
  def validate(event)
    unless event.end_time.blank? || event.end_time >= event.start_time
      event.errors.add :end_time, "cannot be before start time"
    end
  end
end

class Event < ApplicationRecord
  validates_presence_of :name, :start_time, :end_time ,:location
  validates_with DateValidator

  belongs_to :creator, class_name: "User"
  has_many :event_attendances, dependent: :delete_all
  has_many :attendees, through: :event_attendances, class_name: "User"

  scope :upcoming, -> do
    where('start_time > ?', Time.now)
  end

  scope :ongoing, -> do
    where('start_time < ?', Time.now).where('end_time > ?', Time.now)
  end

  scope :past, -> do
    where('end_time < ?', Time.now)
  end

  scope :visible, -> do
    where('private = ?', false)
  end
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :events, foreign_key: :creator_id
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, source: :event,
           class_name: "Event", through: :event_attendances
  has_many :invitations, foreign_key: :invitee_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  def create
    unless user_signed_in?
      flash[:warning] = "Please sign in to register for an event"
      redirect_to new_user_session_url
      return
    end

    unless params[:event] && (event = Event.find_by_id(params[:event]))
      flash[:error] = "Event not found"
      redirect_to root_url
      return
    end

    if current_user.attended_events.include?(event)
      flash[:success] = "You are already registered for this event"
      redirect_to event
      return
    end

    current_user.event_attendances.create(event_id: event.id)
    flash[:success] = "Successfully registered for the event!"
    redirect_to current_user
  end

  def destroy
    unless user_signed_in?
      flash[:warning] = "Please sign in to deregister from an event"
      redirect_to new_user_session_url
      return
    end

    unless params[:event]
      flash[:warning] = "Please choose event to deregister from"
      redirect_to current_user
      return
    end

    if (attendance = EventAttendance.find_by(
        attendee_id: current_user, event_id: params[:event]))
      attendance.destroy
      flash[:success] = "Successfully deregistered from the event."
      redirect_to current_user
    else
      flash[:error] = "Unable to find event"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :require_ownership, only: [:edit, :update, :destroy]

  def index
    @events = Event.visible
    @filter = event_filter || :all
  end

  def show
    @event = Event.find_by_id(params[:id])

    unless @event
      flash[:error] = "Event not found"
      redirect_to root_url
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event details updated successfully!"
      redirect_to current_user
    else
      render :edit
    end
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event created successfully!"
      redirect_to my_events_url
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event deleted successfully!"
    redirect_to current_user
  end

  private

    @@action_display_names = {
      new: "create", create: "create", edit: "edit", update: "edit",
      destroy: "delete"
    }

    def require_login
      unless user_signed_in?
        flash[:warning] =
          "Please sign in to #{@@action_display_names[action_name.to_sym]} events."
          redirect_to new_user_session_url
        return
      end
    end

    def require_ownership
      @event = Event.find_by_id(params[:id])

      unless @event.creator == current_user
        flash[:error] =
          "You cannot #{@@action_display_names[action_name.to_sym]} " \
          "events that someone else created"
        redirect_to root_url
      end
    end

    def event_params
      params.require(:event).permit(:name, :description, :start_time, :end_time,
                                    :location, :private)
    end

    def event_filter
      if params[:filter] && Event.send(:valid_scope_name?, params[:filter])
        params[:filter]
      end
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    unless user_signed_in?
      flash[:warning] = "Please sign in to see your invitations"
      redirect_to new_user_session_url
      return
    end

    @invitations = current_user.invitations
  end

  def create
  end

  def update
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

    def sign_up_params
      params.require(:user).permit(:name, :username, :email, :password,
                                   :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :username, :email, :password,
                                   :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id]
      unless (@user = User.find_by_id(params[:id]))
        flash[:error] = "Non-existent user"
        redirect_to root_url
      end
    elsif user_signed_in?
      @user = current_user
    else
      flash[:warning] = "Please sign in to see your events"
      redirect_to new_user_session_url
    end

    @events = @user&.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendances/create.html.erb
<h1>EventAttendances#create</h1>
<p>Find me in app/views/event_attendances/create.html.erb</p>

app/views/events/_event.html.erb
<article class="event-card card">
  <h3><%= link_to event.name, event %></h3>

  <% if event.description %>
    <p><%= event.description[0, 120] %></p>
  <% end %>

  <%= render 'events/event_details', locals: { event: event } %>
</article>

app/views/events/_event_details.html.erb
<% event = locals[:event] %>

<div class="dates">
  <div><span class="label">Start time:</span> <%= event.start_time %></div>
  <% if event.end_time %>
    <div><span class="label">End time:</span> <%= event.end_time %></div>
  <% end %>
</div>

<div class="location">
  <span class="label">Location:</span> <%= event.location %>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |f| %>
  <%= render 'devise/shared/error_messages', resource: @event %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :private, "Make event private (invitation only)" %>
    <%= f.check_box :private %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<h2><%= @filter.capitalize %> events</h2>
<ul>
  <li><%= link_to 'All events', events_path %></li>
  <li><%= link_to 'Upcoming events', events_path(filter: :upcoming) %></li>
  <li><%= link_to 'Ongoing events', events_path(filter: :ongoing) %></li>
  <li><%= link_to 'Past events', events_path(filter: :past) %></li>
</ul>
<%= render 'shared/unless_empty', locals: { collection: @events.send(@filter) } %>

app/views/events/new.html.erb
<%= form_with model: @event, local: true do |f| %>
  <%= render 'devise/shared/error_messages', resource: @event %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :private, "Make event private (invitation only)" %>
    <%= f.check_box :private %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event-description">
  <h2><%= @event.name %></h2>
  <p>
    Created by: <%= @event.creator.name %>
    (<%= link_to @event.creator.username, @event.creator %>)
  </p>

  <% if @event.description %>
    <p><%= @event.description %></p>
  <% end %>

  <%= render 'events/event_details', locals: { event: @event } %>

  <% if @event.end_time > Time.now %>
    <% if current_user && current_user.attended_events.include?(@event) %>
      <%= link_to "Unregister from this event",
        event_attendances_path(event: @event), method: :delete %>
    <% else %>
      <%= link_to 'Register for this event',
        event_attendances_path(event: @event), method: :post %>
    <% end %>
  <% end %>

  <% if @event.creator == current_user %>
    <%= link_to 'Edit event', edit_event_path(@event) %>
    <%= link_to 'Delete event', @event, method: :delete, style: "color: red;",
      data: { confirm: "Are you sure?" } %>

    <section class="invitations">
      <%# TODO keep working here %>
      <%= form_with url: user_search_url %>
    </section>
  <% end %>

  <section>
    <h3>
      <%= pluralize(@event.attendees.count, "person") %>
      registered for this event
    </h3>

    <ul>
      <% @event.attendees.each do |attendee| %>
        <li><%= link_to attendee.username, attendee %></li>
      <% end %>
    </ul>
  </section>
</div>

app/views/invitations/_invitation.html.erb
<div class="invitation-card card">
  <h3><%= link_to invitation.event.name, invitation.event %></h3>
  <div class="info">
    Invited by: <%= invitation.inviter.name %>
    (<%= invitation.inviter.username %>)
  </div>
  <% if invitation.message %>
    <div class="message">
      <%= invitation.message %>
    </div>
  <% end %>
  <div class="actions">
    <%= link_to 'Accept', invitation_path(accepted: true) %>
    <%= link_to 'Decline', invitation_path(accepted: false) %>
  </div>
</div>

app/views/invitations/index.html.erb
<h2>Invitations</h2>
<%= render 'shared/unless_empty', locals: { collection: @invitations } %>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to 'Private events', root_path %></h1>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to 'Create Event', new_event_path %></li>
        <li><%= link_to 'My Events', my_events_path %></li>
        <li><%= link_to 'Invitations', invitations_path %></li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li><%= link_to 'Log in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "flash flash-#{message_type}") %>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_unless_empty.html.erb
<% collection = locals[:collection] %>
<% if collection.count > 0 %>
  <%= render collection %>
<% else %>
  <em>Nothing to display</em>
<% end %>

app/views/users/show.html.erb
<section>
  <h2>
    <% if @user == current_user %>
      <h2>Your events</h2>
    <% else %>
      Events created by <%= @user.name %> (<%= @user.username %>)
      <% @events = @events.visible %>
    <% end %>
  </h2>

  <%= render 'shared/unless_empty', locals: { collection: @events } %>
</section>

<% if @user == current_user %>
  <% upcoming_events =
    current_user.attended_events.upcoming %>

  <% ongoing_events =
    current_user.attended_events.ongoing %>

  <% past_events =
    current_user.attended_events.past %>

  <section>
    <h2>Upcoming events you are registered for</h2>
    <%= render 'shared/unless_empty', locals: { collection: upcoming_events } %>
  </section>

  <section>
    <h2>Ongoing events you are registered for</h2>
    <%= render 'shared/unless_empty', locals: { collection: ongoing_events } %>
  </section>

  <section>
    <h2>Past events you have attended</h2>
    <%= render 'shared/unless_empty', locals: { collection: past_events } %>
  </section>
<% end %>